"""
Reference dictionary and resolver for standard prescription shorthand and abbreviations.
Used by RxParse to translate clinical shorthand into structured dosage and timing info.
"""

from typing import Dict, List, Optional, Tuple, Any

# Standard numeric matrix frequencies: Morning - Afternoon - Night (or Morning - Noon - Evening - Night)
NUMERIC_SHORTHAND_MAP: Dict[str, Dict[str, Any]] = {
    "1-0-1": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Twice daily (morning and night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1 - 0 - 1": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Twice daily (morning and night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1-1-1": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Three times daily (morning, afternoon, night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1 - 1 - 1": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Three times daily (morning, afternoon, night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1-0-0": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Once daily (morning)",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1 - 0 - 0": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Once daily (morning)",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "0-1-0": {
        "frequency_per_day": 1,
        "suggested_times": ["13:00"],
        "description": "Once daily (afternoon)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "0 - 1 - 0": {
        "frequency_per_day": 1,
        "suggested_times": ["13:00"],
        "description": "Once daily (afternoon)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "0-0-1": {
        "frequency_per_day": 1,
        "suggested_times": ["21:00"],
        "description": "Once daily (night)",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": True,
        "needs_review_time": False,
    },
    "0 - 0 - 1": {
        "frequency_per_day": 1,
        "suggested_times": ["21:00"],
        "description": "Once daily (night)",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": True,
        "needs_review_time": False,
    },
    "1-1-1-1": {
        "frequency_per_day": 4,
        "suggested_times": ["08:00", "12:00", "16:00", "20:00"],
        "description": "Four times daily",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2-1/2-1/2": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Half tablet thrice daily (morning, lunch, night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2 - 1/2 - 1/2": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Half tablet thrice daily (morning, lunch, night)",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2-0-1/2": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Half tablet twice daily",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2 - 0 - 1/2": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Half tablet twice daily",
        "with_food": True,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2-0-0": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Half tablet morning",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "1/2 - 0 - 0": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Half tablet morning",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": False,
        "needs_review_time": False,
    },
    "0-0-1/2": {
        "frequency_per_day": 1,
        "suggested_times": ["21:00"],
        "description": "Half tablet at night",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": True,
        "needs_review_time": False,
    },
    "0 - 0 - 1/2": {
        "frequency_per_day": 1,
        "suggested_times": ["21:00"],
        "description": "Half tablet at night",
        "with_food": False,
        "empty_stomach": False,
        "bedtime_only": True,
        "needs_review_time": False,
    },
}

# Latin and clinical frequency abbreviations
LATIN_FREQUENCY_MAP: Dict[str, Dict[str, Any]] = {
    "od": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Once daily (omne in die)",
        "needs_review_time": False,
    },
    "qd": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Once daily (quaque die)",
        "needs_review_time": False,
    },
    "bd": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Twice daily (bis in die)",
        "needs_review_time": False,
    },
    "bid": {
        "frequency_per_day": 2,
        "suggested_times": ["08:00", "20:00"],
        "description": "Twice daily (bis in die)",
        "needs_review_time": False,
    },
    "tds": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Three times daily (ter die sumendus)",
        "needs_review_time": False,
    },
    "tid": {
        "frequency_per_day": 3,
        "suggested_times": ["08:00", "14:00", "20:00"],
        "description": "Three times daily (ter in die)",
        "needs_review_time": False,
    },
    "qid": {
        "frequency_per_day": 4,
        "suggested_times": ["08:00", "12:00", "16:00", "20:00"],
        "description": "Four times daily (quater in die)",
        "needs_review_time": False,
    },
    "qds": {
        "frequency_per_day": 4,
        "suggested_times": ["08:00", "12:00", "16:00", "20:00"],
        "description": "Four times daily (quater die sumendus)",
        "needs_review_time": False,
    },
    "hs": {
        "frequency_per_day": 1,
        "suggested_times": ["21:30"],
        "bedtime_only": True,
        "description": "At bedtime (hora somni)",
        # Bedtime is an estimate per patient routine, so flag for user review
        "needs_review_time": True,
    },
    "qhs": {
        "frequency_per_day": 1,
        "suggested_times": ["21:30"],
        "bedtime_only": True,
        "description": "Every night at bedtime",
        "needs_review_time": True,
    },
    "sos": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "As needed / In emergency (si opus sit)",
        "notes": "Take as needed (SOS)",
        "needs_review_time": True,
    },
    "prn": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "As needed (pro re nata)",
        "notes": "Take as needed (PRN)",
        "needs_review_time": True,
    },
    "stat": {
        "frequency_per_day": 1,
        "suggested_times": ["08:00"],
        "description": "Immediate / Single dose (Statim)",
        "notes": "Immediate single dose (Stat)",
        "needs_review_time": False,
    },
}

# Meal condition modifiers
MEAL_MODIFIER_MAP: Dict[str, Dict[str, Any]] = {
    "before breakfast": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before breakfast",
    },
    "before dinner": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before dinner",
    },
    "after breakfast": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After breakfast",
    },
    "after dinner": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After dinner",
    },
    "after lunch": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After lunch",
    },
    "ac": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before food (ante cibum)",
    },
    "ante cibum": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before food",
    },
    "pc": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After food (post cibum)",
    },
    "post cibum": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After food",
    },
    "bb": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before breakfast",
    },
    "after food": {
        "with_food": True,
        "empty_stomach": False,
        "description": "After food",
    },
    "before food": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Before food",
    },
    "with food": {
        "with_food": True,
        "empty_stomach": False,
        "description": "With food",
    },
    "empty stomach": {
        "empty_stomach": True,
        "with_food": False,
        "description": "Empty stomach",
    },
}
