/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppAdherenceLogRouteImport } from './routes/_app.adherence-log'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCyclesRouteImport } from './routes/_app.cycles'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGenericFinderRouteImport } from './routes/_app.generic-finder'
import { Route as AppHospitalsRouteImport } from './routes/_app.hospitals'
import { Route as AppMedicationsRouteImport } from './routes/_app.medications'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppReportsIdRouteImport } from './routes/_app.reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdherenceLogRoute = AppAdherenceLogRouteImport.update({
  id: '/adherence-log',
  path: '/adherence-log',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCyclesRoute = AppCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGenericFinderRoute = AppGenericFinderRouteImport.update({
  id: '/generic-finder',
  path: '/generic-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationsRoute = AppMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/adherence-log': typeof AppAdherenceLogRoute
  '/chat': typeof AppChatRoute
  '/cycles': typeof AppCyclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/generic-finder': typeof AppGenericFinderRoute
  '/hospitals': typeof AppHospitalsRoute
  '/medications': typeof AppMedicationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/adherence-log': typeof AppAdherenceLogRoute
  '/chat': typeof AppChatRoute
  '/cycles': typeof AppCyclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/generic-finder': typeof AppGenericFinderRoute
  '/hospitals': typeof AppHospitalsRoute
  '/medications': typeof AppMedicationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/adherence-log': typeof AppAdherenceLogRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/cycles': typeof AppCyclesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/generic-finder': typeof AppGenericFinderRoute
  '/_app/hospitals': typeof AppHospitalsRoute
  '/_app/medications': typeof AppMedicationsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
  '/_app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/adherence-log'
    | '/chat'
    | '/cycles'
    | '/dashboard'
    | '/generic-finder'
    | '/hospitals'
    | '/medications'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/reports/$id'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/adherence-log'
    | '/chat'
    | '/cycles'
    | '/dashboard'
    | '/generic-finder'
    | '/hospitals'
    | '/medications'
    | '/notifications'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/reports/$id'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/adherence-log'
    | '/_app/chat'
    | '/_app/cycles'
    | '/_app/dashboard'
    | '/_app/generic-finder'
    | '/_app/hospitals'
    | '/_app/medications'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/reports/$id'
    | '/_app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/adherence-log': {
      id: '/_app/adherence-log'
      path: '/adherence-log'
      fullPath: '/adherence-log'
      preLoaderRoute: typeof AppAdherenceLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cycles': {
      id: '/_app/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AppCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generic-finder': {
      id: '/_app/generic-finder'
      path: '/generic-finder'
      fullPath: '/generic-finder'
      preLoaderRoute: typeof AppGenericFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospitals': {
      id: '/_app/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medications': {
      id: '/_app/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AppMedicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIdRoute: AppReportsIdRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAdherenceLogRoute: typeof AppAdherenceLogRoute
  AppChatRoute: typeof AppChatRoute
  AppCyclesRoute: typeof AppCyclesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGenericFinderRoute: typeof AppGenericFinderRoute
  AppHospitalsRoute: typeof AppHospitalsRoute
  AppMedicationsRoute: typeof AppMedicationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdherenceLogRoute: AppAdherenceLogRoute,
  AppChatRoute: AppChatRoute,
  AppCyclesRoute: AppCyclesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGenericFinderRoute: AppGenericFinderRoute,
  AppHospitalsRoute: AppHospitalsRoute,
  AppMedicationsRoute: AppMedicationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
