"""
Curated drug interaction dataset.
Sourced from publicly available medical references. Each entry includes
its source for traceability. This is a simplified educational dataset,
NOT a substitute for a licensed clinical drug interaction database.
Compiled: July 2026.
"""

CURATED_INTERACTIONS = [
    {
        "drug_a": "warfarin",
        "drug_b": "aspirin",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "Increases bleeding risk; aspirin inhibits platelet aggregation while warfarin reduces clotting-factor synthesis.",
        "source": "Drugs.com / NCBI StatPearls",
        "source_url": "https://www.ncbi.nlm.nih.gov/books/NBK441964/",
    },
    {
        "drug_a": "warfarin",
        "drug_b": "ibuprofen",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "NSAIDs increase bleeding risk when combined with warfarin.",
        "source": "NCBI StatPearls",
        "source_url": "https://www.ncbi.nlm.nih.gov/books/NBK441964/",
    },
    {
        "drug_a": "levothyroxine",
        "drug_b": "calcium",
        "severity": "moderate",
        "minimum_gap_hours": 4.0,
        "description": "Calcium can bind to levothyroxine and reduce its absorption.",
        "source": "GoodRx Health",
        "source_url": "https://www.goodrx.com/conditions/hypothyroidism/is-my-thyroid-medication-working-these-drugs-can-cause-interactions",
    },
    {
        "drug_a": "levothyroxine",
        "drug_b": "iron",
        "severity": "moderate",
        "minimum_gap_hours": 4.0,
        "description": "Iron supplements reduce levothyroxine absorption; separate dosing by at least 4 hours.",
        "source": "GoodRx Health",
        "source_url": "https://www.goodrx.com/conditions/hypothyroidism/is-my-thyroid-medication-working-these-drugs-can-cause-interactions",
    },
    {
        "drug_a": "levothyroxine",
        "drug_b": "omeprazole",
        "severity": "moderate",
        "minimum_gap_hours": 4.0,
        "description": "Proton pump inhibitors reduce levothyroxine absorption.",
        "source": "GoodRx Health",
        "source_url": "https://www.goodrx.com/conditions/hypothyroidism/is-my-thyroid-medication-working-these-drugs-can-cause-interactions",
    },
    {
        "drug_a": "lisinopril",
        "drug_b": "ibuprofen",
        "severity": "moderate",
        "minimum_gap_hours": 6.0,
        "description": "NSAIDs can blunt the blood-pressure-lowering effect of ACE inhibitors like lisinopril.",
        "source": "CheckDrugInteractions.com",
        "source_url": "https://www.checkdruginteractions.com/",
    },
    {
        "drug_a": "lisinopril",
        "drug_b": "potassium",
        "severity": "major",
        "minimum_gap_hours": 6.0,
        "description": "Combination can cause dangerously high potassium levels (hyperkalemia).",
        "source": "Mountain Care Pharmacy",
        "source_url": "https://mtncarerx.com/the-top-10-most-common-medication-interactions-and-how-to-avoid-them/",
    },
    {
        "drug_a": "simvastatin",
        "drug_b": "amiodarone",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "Amiodarone inhibits the enzyme that metabolizes simvastatin, raising blood levels and increasing risk of myopathy.",
        "source": "CheckDrugInteractions.com",
        "source_url": "https://www.checkdruginteractions.com/",
    },
    {
        "drug_a": "digoxin",
        "drug_b": "quinidine",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "Quinidine increases digoxin levels, risking toxicity.",
        "source": "Mountain Care Pharmacy",
        "source_url": "https://mtncarerx.com/the-top-10-most-common-medication-interactions-and-how-to-avoid-them/",
    },
    {
        "drug_a": "sertraline",
        "drug_b": "warfarin",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "SSRIs like sertraline increase bleeding risk when combined with warfarin.",
        "source": "NCBI StatPearls",
        "source_url": "https://www.ncbi.nlm.nih.gov/books/NBK441964/",
    },
    {
        "drug_a": "alprazolam",
        "drug_b": "tramadol",
        "severity": "major",
        "minimum_gap_hours": 12.0,
        "description": "Combined use increases risk of sedation and respiratory depression.",
        "source": "MyMedicineAdvisor",
        "source_url": "https://mymedicineadvisor.com/health/drug-interactions-list/",
    },
]